name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-slim

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Set up Python environment with version 3.11
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Verify game module can be imported
    - name: Verify game module
      run: |
        python -c "import mage_vs_orc; print('✅ Game module imports successfully')"
        python -c "import mage_vs_orc; game = mage_vs_orc.Game(); print('✅ Game initializes successfully')"
